
server:
  port: 9090
  
  
#data base specific properties
spring:
   datasource:
     url: jdbc:mysql://localhost:3306/arm
     username: root
     password: root
   jpa:
     hibernate:
       ddl-auto: none
     database-platform: org.hibernate.dialect.MySQL5Dialect
   flyway:
     enabled: true
     locations:
       classpath: db/migration
     baselineOnMigrate: true






##data base specific properties
# spring:
#     datasource:
#       url: jdbc:mysql://localhost:3306/arm
#       username: root
#       password: root
#     jpa:
#       hibernate:
#         ddl-auto: none
#       database-platform: org.hibernate.dialect.MySQL5Dialect


#  h2:
#    console:
#      enabled: true

#key clock related properties
keycloak:
  realm: myrealm
  auth-server-url: http://localhost:8180/auth
  resource: myclient
  public-client: true
  bearer-only: true

