##data base specific properties
#spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/arm
#      username: root
#      password: root
#    jpa:
#      hibernate:
#        ddl-auto: none
#      database-platform: org.hibernate.dialect.MySQL5Dialect
#    flyway:
#      enabled: true
#      locations:
#        classpath: db/migration
